/**
 * Skill: MIP widgets — the FULL set of widget types the agent can create, the
 * settings each renderer reads, and how to size + arrange them. If a type is in
 * this list, you CAN build it — never claim a type is unavailable.
 */

export const MIP_WIDGETS_SKILL = [
    "## Skill: MIP widgets",
    "A dashboard is a 12-column grid (rows ≈ 70px tall). A widget has a `type`, optional `title`, `settings` (inline data), and an optional `data` binding (live REST). You can create ANY of the types below — do not say a type is unsupported.",
    "",
    "### Data & charts",
    "  kpi        settings:{ value, delta?, deltaLabel?, unit?, valueFormat? }",
    "  progress   settings:{ value, target, label? }",
    "  lineChart | barChart | areaChart | pieChart | donutChart  settings:{ points:[{label,value},…], legendPosition?: 'bottom'|'top'|'left'|'right'|'none' }",
    "  table      settings:{ columns:[{key,label},…], rows:[{…},…] }",
    "  list       settings:{ primaryKey, secondaryKey?, items:[{…},…] }",
    "  detail     settings:{ fields:[{key,label},…], record:{…} }",
    "",
    "### Diagrams (mermaid) — settings:{ source: '<mermaid text>' }",
    "  ganttChart       → source: 'gantt\\n  title …\\n  dateFormat YYYY-MM-DD\\n  section A\\n  Task :a1, 2026-01-01, 14d'",
    "  flowchart        → source: 'graph TD\\n  A-->B'",
    "  sequenceDiagram  → source: 'sequenceDiagram\\n  A->>B: msg'",
    "  mindmap          → source: 'mindmap\\n  root((X))\\n    A'",
    "  timeline         → source: 'timeline\\n  title …\\n  2026 Q1 : item'",
    "",
    "### Content & layout",
    "  markdown   settings:{ content }   ·   card  settings:{ heading, body, alignment? }",
    "  image      settings:{ url, alt?, fit? }   ·   pageHeader settings:{ heading, subheading?, actionLabel?, actionUrl?, alignment? }",
    "  button     settings:{ label, url?, target?, className?, title? }",
    "  tabs       settings:{ tabs:[{label, content},…] }   ·   googleMap settings:{ query | lat,lng, zoom? }",
    "  modal / drawer  settings:{ triggerLabel, heading, body }",
    "",
    "### Marketing blocks (icons are Untitled names like 'Zap' or icon-font classes, NOT emojis)",
    "  hero        settings:{ heading, subheading?, eyebrow?, backgroundImage?, alignment?, ctaLabel?, ctaUrl? }",
    "  cta         settings:{ heading, body?, buttonLabel?, buttonUrl?, alignment? }",
    "  featureGrid settings:{ heading?, features:[{icon, title, description},…] }",
    "  statsGrid   settings:{ heading?, stats:[{value, label, delta?},…] }",
    "  pricing     settings:{ heading?, tiers:[{name, price, period?, features:[…], highlighted?, ctaLabel?},…] }",
    "  testimonial settings:{ quote, author, role?, rating? }   ·   faq settings:{ heading?, items:[{question, answer},…] }",
    "  contentSection settings:{ heading, body?, imageUrl?, imagePosition?, alignment? }",
    "",
    "### Sizing (grid units; w out of 12, rows ≈ 70px). Omit { w, h } to use the per-type default, or set them to compose a layout. Typical:",
    "  kpi/progress w3 h2 (four across)  ·  charts w6 h6  ·  pie/donut w4 h6  ·  table w6–12 h8  ·  list w4–6 h6",
    "  diagrams w6–8 h6  ·  hero/cta/pricing/contentSection w12  ·  faq/featureGrid/statsGrid w8 h6",
    "",
    "### Composition — most important first: a row of KPIs on top, then wide trend charts, comparisons as bars, parts-of-whole as pie/donut, detail tables/lists lower & wider. Keep each row's widths summing to ~12 so rows align; group related widgets.",
].join("\n");
